version: "3.8"

services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.92.0
    platform: linux/amd64
    command:
      - "--config"
      - /etc/otel/config.yml
    ports:
      - 4317:4317
    volumes:
      - ./docker/otel-collector/config.yml:/etc/otel/config.yml
  # https://www.jaegertracing.io/docs/1.53/getting-started/
  jaeger:
    image: jaegertracing/all-in-one:1.48
    expose:
      # gRPC 経由で OpenTelemetry Protocol (OTLP) を受け入れる
      - 4317
    ports:
      # フロントエンドを提供する
      - 16686:16686